trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - v*
  paths:
      exclude:
        - README.adoc
        - LICENSE
jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: gcc -std=c99 -pedantic -Wextra -O3 -o patcher main.c patches.c
      displayName: 'Build'

    - bash: |
        export RELEASE_TAG=$(git describe)
        echo "##vso[task.setvariable variable=release_tag]$RELEASE_TAG"
        mv $SYSTEM_DEFAULTWORKINGDIRECTORY/patcher $BUILD_ARTIFACTSTAGINGDIRECTORY/patcher
      displayName: Move binary to artifact directory

    - task: GitHubRelease@1
      condition: startswith(variables['Build.SourceBranch'], 'refs/tags/')
      displayName: Create GitHub release
      inputs:
          gitHubConnection: releases
          title: $(release_tag)
          tagPattern: ^v(\d+\.)+(\d+\.)+(\*|\d+)$
    - task: PublishBuildArtifacts@1
      displayName: Upload binary to artifacts
      inputs:
            artifactName: patcher
            pathToPublish: $(Build.ArtifactStagingDirectory)
